---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../labconfig.yml
  tasks:
    - name: Initialize node - loadbalancer @ 192.168.100.140
      include: init-container.yml container_name=loadbalancer      lab_ip=192.168.100.140