---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../labconfig.yml
  tasks:
    - name: Initialize node - web2 @ 192.168.100.142
      include: init-container.yml container_name=web2              lab_ip=192.168.100.142