---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../labconfig.yml
  tasks:
    - name: Initialize node - web1 @ 192.168.100.141
      include_tasks:
        file: init-container.yml container_name=web1              lab_ip=192.168.100.141