---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../labconfig.yml
  tasks:
    - name: Initialize node - front @ 192.168.100.145
      include: init-container.yml container_name=front             lab_ip=192.168.100.145