---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../labconfig.yml
  tasks:
    - name: Initialize node - metrics @ 192.168.100.144
      include: init-container.yml container_name=metrics           lab_ip=192.168.100.144