---
# This playbook will install PostgreSQL and create db user and give permissions and enable pg_stat_statements extension.

# mkdir /root/shared/
# mount -t vboxsf loadlab_vm /root/shared/
# cd /root/shared/ansible/deployment/
# ./deploy-postgres.sh

- name: Install the repository RPM
  package:
    name:
      - https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  when: config_only == false

- name: Install PostgreSQL package
  package:
    name:
      - postgresql10-server
      - postgresql10
      - postgresql10-libs
      - postgresql10-contrib
    state: present
  when: config_only == false


- name: Install PostreSQL monitoring
  package:
    name:
      - python-psycopg2
    state: present
  when: config_only == false