---

- name: Install MySQL-python and deps
  yum: 
    name: MySQL-python 
    state: present 
    skip_broken: true    
  when: config_only == false

- name: Download WordPress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"
  when: config_only == false

- name: Delete Folder wordpress
  command: rm -rf /srv/wordpress
  when: config_only == false

- name: Extract archive
  command: chdir=/srv/ /bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates=/srv/wordpress
  when: config_only == false