{
 "title": "PostgreSQL Query Details",
 "tags": [
  "influxdb",
  "PostgreSQL"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "db_jmeter", "label": "DataBase for annotation", "query": "influxdb" },
   { "name": "db", "label": "DataBase", "query": "influxdb" },
   { "name": "archive", "label": "Retention policy (archive)", "query": "SHOW RETENTION POLICIES" },
   { "name": "new", "label": "Retention Policy (new)", "query": "SHOW RETENTION POLICIES" },
   { "name": "queryid", "label": "queryid", "query": "4281998489" },
   {
    "name": "host",
    "label": "PostgreSQL host",
    "query": "SELECT DISTINCT(\"host\") FROM (SELECT last(\"calls_10m\") FROM \"${archive}\".\"pg_stat_statements_query_md5\" WHERE \"queryid\"=~/^${queryid:regex}$/ AND $timeFilter GROUP BY \"host\")"
   },
   {
    "name": "datname",
    "label": "PostgreSQL DB",
    "query": "SELECT DISTINCT(\"datname\") FROM (SELECT last(\"calls_10m\") FROM \"${archive}\".\"pg_stat_statements_query_md5\" WHERE \"queryid\"=~/^${queryid:regex}$/ AND \"host\" =~ /^${host:regex}$/ AND $timeFilter GROUP BY \"datname\")"
   },
   {
    "name": "usename",
    "label": "PostgreSQL User",
    "query": "SELECT DISTINCT(\"usename\") FROM (SELECT last(\"calls_10m\") FROM \"${archive}\".\"pg_stat_statements_query_md5\" WHERE $timeFilter AND \"queryid\"=~/^${queryid:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"host\" =~ /^${host:regex}$/  GROUP BY \"usename\")"
   },
   {
    "name": "query_md5",
    "query": "SELECT DISTINCT(\"query_md5\") FROM (SELECT last(\"calls_10m\") FROM \"${archive}\".\"pg_stat_statements_query_md5\" WHERE \"datname\" =~ /^${datname:regex}$/ AND \"queryid\" =~ /^${queryid:regex}$/  AND $timeFilter GROUP BY \"query_md5\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Сводная статистика по QueryID = ${queryid}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 23, "x": 0, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "calls_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Calls" ], "type": "alias" }
        ],
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ],
        [
         { "params": [ "rows_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Rows" ], "type": "alias" }
        ],
        [
         { "params": [ "max_time_10m" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Max" ], "type": "alias" }
        ],
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / sum(\"calls_10m\")"
          ],
          "type": "math"
         },
         { "params": [ "Mean" ], "type": "alias" }
        ],
        [
         { "params": [ "shared_blks_hit_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / ( sum(\"shared_blks_hit_10m\") + sum(\"shared_blks_read_10m\"))"
          ],
          "type": "math"
         },
         { "params": [ "% Shared Hit" ], "type": "alias" }
        ],
        [
         { "params": [ "local_blks_hit_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / ( sum(\"local_blks_hit_10m\") + sum(\"local_blks_read_10m\"))"
          ],
          "type": "math"
         },
         { "params": [ "% Local Hit" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
       ]
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 4, "w": 23, "x": 0, "y": 4 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "query_md5" ], "type": "tag" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "calls_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Calls" ], "type": "alias" }
        ],
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ],
        [
         { "params": [ "rows_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Rows" ], "type": "alias" }
        ],
        [
         { "params": [ "max_time_10m" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Max" ], "type": "alias" }
        ],
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / sum(\"calls_10m\")"
          ],
          "type": "math"
         },
         { "params": [ "Mean" ], "type": "alias" }
        ],
        [
         { "params": [ "shared_blks_hit_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / ( sum(\"shared_blks_hit_10m\") + sum(\"shared_blks_read_10m\"))"
          ],
          "type": "math"
         },
         { "params": [ "% Shared Hit" ], "type": "alias" }
        ],
        [
         { "params": [ "local_blks_hit_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / ( sum(\"local_blks_hit_10m\") + sum(\"local_blks_read_10m\"))"
          ],
          "type": "math"
         },
         { "params": [ "% Local Hit" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
       ]
      }
     ]
    },
    {
     "title": "Sum: Query Duration / min",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "($tag_host) $tag_query_md5",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "query_md5" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/($__interval_ms / 1000 / 60)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
       ]
      }
     ]
    },
    {
     "title": "Query duration / DB duration",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 7, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "Sum Duration per minute by Query",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "query": "SELECT sum(\"duration_10m\") as \"Sum Duration per minute by Query\" FROM \"$archive\".\"pg_stat_statements_query_md5\" WHERE (\"datname\" =~ /^$datname$/ AND \"host\" =~ /^$host$/ AND \"usename\" =~ /^$usename$/ AND \"queryid\" =~ /^$queryid$/ AND \"query_md5\" =~ /^$query_md5$/) AND $timeFilter GROUP BY time($__interval), \"query_md5\" fill(null)",
       "select": [
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           "Sum Duration per minute by Query"
          ],
          "type": "alias"
         }
        ]
       ],
       "tags": [
        { "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
       ]
      },
      {
       "alias": "Sum Duration per minute by DB",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "query": "SELECT sum(\"duration_10m\") as \"Sum Duration per minute by DB\" FROM \"$archive\".\"pg_stat_statements_query_md5\" WHERE (\"datname\" =~ /^$datname$/ AND \"host\" =~ /^$host$/ AND \"usename\" =~ /^$usename$/) AND $timeFilter GROUP BY time($__interval), \"query_md5\" fill(null)",
       "select": [
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Sum Duration per minute by DB" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
       ]
      }
     ]
    },
    {
     "title": "Avg (Query Duration)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_query_md5 ($tag_host)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "query_md5" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/sum(calls_10m)" ], "type": "math" },
         { "params": [ "Avg" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
       ]
      }
     ]
    },
    {
     "title": "Query Calls",
     "type": "graph",
     "description": "Средняя интенсивность вызовов запроса за минуту.\nИзмеряется в запросах в сек (RPS)",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "alias": "($tag_host) $tag_query_md5",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "query_md5" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "calls_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / ($__interval_ms / 1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
       ]
      }
     ]
    },
    {
     "title": "Query Calls / DB Calls",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 7, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "RPS Query",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "calls_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
       ]
      },
      {
       "alias": "RPS DB",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "calls_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
       ]
      }
     ]
    },
    {
     "title": "Avg (Query Rows)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_query_md5 ($tag_host)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "query_md5" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "rows_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/sum(calls_10m)" ], "type": "math" },
         { "params": [ "Avg" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
       ]
      }
     ]
    },
    {
     "title": "Query Text of $query_md5",
     "type": "table-old",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 18 },
     "repeat": "query_md5",
     "targets": [
      {
       "groupBy": [
        { "params": [ "query" ], "type": "tag" }
       ],
       "measurement": "pg_stat_statements_diff",
       "query": "SELECT last(\"calls\") FROM \"$archive\".\"pg_stat_statements_diff\" WHERE (\"query_md5\" =~ /^$query_md5$/ AND \"queryid\" =~ /^$queryid$/ AND \"datname\" =~ /^$datname$/) GROUP BY \"query\"",
       "select": [
        [
         { "params": [ "calls" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "query_md5", "operator": "=~", "value": "/^$query_md5$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Детальная статистика по QueryID = ${queryid} (есть данные только за последние 7 дней)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sum: Query Duration / min",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_query_md5 ($tag_host)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "query_md5" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_diff",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/($__interval_ms / 1000 / 60)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
       ]
      }
     ]
    },
    {
     "title": "Query duration / DB duration",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 7, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "Sum Duration per minute by Query",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_diff",
       "query": "SELECT sum(\"duration_10m\") as \"Sum Duration per minute by Query\" FROM \"$archive\".\"pg_stat_statements_query_md5\" WHERE (\"datname\" =~ /^$datname$/ AND \"host\" =~ /^$host$/ AND \"usename\" =~ /^$usename$/ AND \"queryid\" =~ /^$queryid$/ AND \"query_md5\" =~ /^$query_md5$/) AND $timeFilter GROUP BY time($__interval), \"query_md5\" fill(null)",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           "Sum Duration per minute by Query"
          ],
          "type": "alias"
         }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
       ]
      },
      {
       "alias": "Sum Duration per minute by DB",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_diff",
       "query": "SELECT sum(\"duration_10m\") as \"Sum Duration per minute by DB\" FROM \"$archive\".\"pg_stat_statements_query_md5\" WHERE (\"datname\" =~ /^$datname$/ AND \"host\" =~ /^$host$/ AND \"usename\" =~ /^$usename$/) AND $timeFilter GROUP BY time($__interval), \"query_md5\" fill(null)",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Sum Duration per minute by DB" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
       ]
      }
     ]
    },
    {
     "title": "Avg (Query Duration)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_query_md5",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "query_md5" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_diff",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/sum(calls)" ], "type": "math" },
         { "params": [ "Avg" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
       ]
      }
     ]
    },
    {
     "title": "Query Calls",
     "type": "graph",
     "description": "Средняя интенсивность вызовов запроса за минуту.\nИзмеряется в запросах в сек (RPS)",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "alias": "$tag_query_md5 ($tag_host)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "query_md5" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_diff",
       "select": [
        [
         { "params": [ "calls" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / ($__interval_ms / 1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
       ]
      }
     ]
    },
    {
     "title": "Query Calls / DB Calls",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 7, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "RPS Query",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_diff",
       "select": [
        [
         { "params": [ "calls" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
       ]
      },
      {
       "alias": "RPS DB",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_diff",
       "select": [
        [
         { "params": [ "calls" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
       ]
      }
     ]
    },
    {
     "title": "Avg (Query Rows)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_query_md5 ($tag_host)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "query_md5" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_diff",
       "select": [
        [
         { "params": [ "rows" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/sum(calls)" ], "type": "math" },
         { "params": [ "Avg" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Детальная статистика по Query c MD5 = $query_md5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "query_md5",
   "collapsed": true,
   "panels": [
    {
     "type": "table-old",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "queryid" ], "type": "tag" },
        { "params": [ "query_md5" ], "type": "tag" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "calls_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Calls" ], "type": "alias" }
        ],
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ],
        [
         { "params": [ "rows_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Rows" ], "type": "alias" }
        ],
        [
         { "params": [ "max_time_10m" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Max" ], "type": "alias" }
        ],
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / sum(\"calls_10m\")"
          ],
          "type": "math"
         },
         { "params": [ "Mean" ], "type": "alias" }
        ],
        [
         { "params": [ "shared_blks_hit_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / ( sum(\"shared_blks_hit_10m\") + sum(\"shared_blks_read_10m\"))"
          ],
          "type": "math"
         },
         { "params": [ "% Shared Hit" ], "type": "alias" }
        ],
        [
         { "params": [ "local_blks_hit_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / ( sum(\"local_blks_hit_10m\") + sum(\"local_blks_read_10m\"))"
          ],
          "type": "math"
         },
         { "params": [ "% Local Hit" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" },
        { "condition": "AND", "key": "query_md5", "operator": "=~", "value": "/^$query_md5$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
       ]
      }
     ]
    },
    {
     "title": "Query Text",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "query" ], "type": "tag" }
       ],
       "measurement": "pg_stat_statements_diff",
       "query": "SELECT last(\"calls\") FROM \"$archive\".\"pg_stat_statements_diff\" WHERE (\"query_md5\" =~ /^$query_md5$/ AND \"queryid\" =~ /^$queryid$/ AND \"datname\" =~ /^$datname$/) GROUP BY \"query\"",
       "select": [
        [
         { "params": [ "calls" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "query_md5", "operator": "=~", "value": "/^$query_md5$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" }
       ]
      }
     ]
    },
    {
     "title": "Sum: Query Duration / min",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Sum Duration per minute by Query ($tag_host)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/($__interval_ms / 1000 / 60)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" },
        { "condition": "AND", "key": "query_md5", "operator": "=~", "value": "/^$query_md5$/" }
       ]
      }
     ]
    },
    {
     "title": "Query duration / DB duration",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "Sum Duration per minute by Query",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" },
        { "condition": "AND", "key": "query_md5", "operator": "=~", "value": "/^$query_md5$/" }
       ]
      },
      {
       "alias": "Sum Duration per minute by DB",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
       ]
      }
     ]
    },
    {
     "title": "Avg (Query Duration)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$col ($tag_host)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/sum(calls_10m)" ], "type": "math" },
         { "params": [ "Avg" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" },
        { "condition": "AND", "key": "query_md5", "operator": "=~", "value": "/^$query_md5$/" }
       ]
      }
     ]
    },
    {
     "title": "Query Calls",
     "type": "graph",
     "description": "Средняя интенсивность вызовов запроса за минуту.\nИзмеряется в запросах в сек (RPS)",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "alias": "RPS ($tag_host)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "calls_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / ($__interval_ms / 1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" },
        { "condition": "AND", "key": "query_md5", "operator": "=~", "value": "/^$query_md5$/" }
       ]
      }
     ]
    },
    {
     "title": "Query Calls / DB Calls",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "RPS Query",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "calls_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" },
        { "condition": "AND", "key": "query_md5", "operator": "=~", "value": "/^$query_md5$/" }
       ]
      },
      {
       "alias": "RPS DB",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "calls_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
       ]
      }
     ]
    },
    {
     "title": "Avg (Query Rows)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$col ($tag_host)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "rows_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/sum(calls_10m)" ], "type": "math" },
         { "params": [ "Avg" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" },
        { "condition": "AND", "key": "query_md5", "operator": "=~", "value": "/^$query_md5$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}