{
 "title": "PostgreSQL Query Statistics",
 "tags": [
  "influxdb",
  "PostgreSQL",
  "main"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "current",
    "query": "/d/pgstat/postgresql-query-statistics"
   },
   {
    "name": "detail",
    "query": "/d/pgquery/postgresql-query-details"
   },
   { "name": "db_test_runs", "label": "DataBase for annotation", "query": "influxdb" },
   { "name": "db", "label": "DataBase", "query": "influxdb" },
   { "name": "archive", "label": "Retention policy (archive)", "query": "SHOW RETENTION POLICIES" },
   { "name": "new", "label": "Retention Policy (new)", "query": "SHOW RETENTION POLICIES" },
   {
    "name": "host",
    "label": "PostgreSQL host",
    "query": "SELECT DISTINCT(\"host\") FROM (SELECT last(\"calls_10m\") FROM \"${archive}\".\"pg_stat_statements_query_md5\"  WHERE $timeFilter GROUP BY \"host\")"
   },
   {
    "name": "datname",
    "label": "PostgreSQL DB",
    "query": "SELECT DISTINCT(\"datname\") FROM (SELECT last(\"calls_10m\") FROM \"${archive}\".\"pg_stat_statements_query_md5\" WHERE \"host\" =~ /^${host:regex}$/   AND $timeFilter GROUP BY \"datname\")"
   },
   {
    "name": "usename",
    "label": "PostgreSQL User",
    "query": "SELECT DISTINCT(\"usename\") FROM (SELECT last(\"calls_10m\") FROM \"${archive}\".\"pg_stat_statements_query_md5\" WHERE \"datname\" =~ /^${datname:regex}$/ AND \"host\" =~ /^${host:regex}$/  AND $timeFilter GROUP BY \"usename\")"
   },
   { "name": "TOP", "query": "10,20,30,40,50,100,200" },
   { "name": "TOP_by", "label": "TOP by", "query": "Total, Calls, Mean, Rows" },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 14, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "pg_stat_statements_query_md5",
     "query": "SELECT \"host\", top(\"factor\", 1) FROM\n(SELECT (sum(\"duration_10m\")*sum(\"calls_10m\")) as \"factor\" FROM \"$archive\".\"pg_stat_statements_query_md5\" WHERE $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "duration_10m" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "calls_10m" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Statistics: Host / Database / User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Duration / min",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *60 /( $__interval_ms / 1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Calls / sec",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "calls_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "  / ($__interval_ms / 1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Duration / min",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_datname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " * 60 / ($__interval_ms / 1000)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Calls / sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_datname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "calls_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/ ($__interval_ms / 1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" }
       ]
      }
     ]
    },
    {
     "title": "$db Statistic",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "calls_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Calls" ], "type": "alias" }
        ],
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ],
        [
         { "params": [ "rows_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Rows" ], "type": "alias" }
        ],
        [
         { "params": [ "max_time_10m" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Max" ], "type": "alias" }
        ],
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / sum(\"calls_10m\")"
          ],
          "type": "math"
         },
         { "params": [ "Mean" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics: Query - TOP ${TOP} by ${TOP_by}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "$db Statistic by query",
     "type": "table",
     "gridPos": { "h": 28, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "queryid" ], "type": "tag" }
       ],
       "measurement": "pg_stat_statements_query_text",
       "query": "SELECT top(\"${TOP_by}\", ${TOP}), \"Calls\", \"Total\", \"Rows\",\"Mean\", \"datname\", \"usename\", \"queryid\", \"query_md5\", \"query\" FROM \n(\nSELECT sum(\"calls\") AS \"Calls\", sum(\"duration\") AS \"Total\", sum(\"rows\") AS \"Rows\", sum(\"duration\")  / sum(\"calls\") AS \"Mean\" FROM \"$new\".\"pg_stat_statements_diff\" WHERE (\"datname\" =~ /^${datname:regex}$/ AND \"host\" =~ /^${host:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND \"query\" =~/.*${filter:regex}.*/ AND  $timeFilter AND time > now()-$new GROUP BY \"host\", \"datname\", \"usename\", \"queryid\", \"query_md5\", \"query\"\n),\n(\nSELECT sum(\"calls\") AS \"Calls\", sum(\"duration\") AS \"Total\", sum(\"rows\") AS \"Rows\", sum(\"duration\")  / sum(\"calls\") AS \"Mean\" FROM \"$archive\".\"pg_stat_statements_diff\" WHERE (\"datname\" =~ /^${datname:regex}$/ AND \"host\" =~ /^${host:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND \"query\" =~/.*${filter:regex}.*/ AND $timeFilter AND time < now()-$new GROUP BY \"host\", \"datname\", \"usename\", \"queryid\", \"query_md5\", \"query\"\n)",
       "select": [
        [
         { "params": [ "query" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         { "params": [ "query" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics: Query (multiline) - TOP ${TOP} by ${TOP_by}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$db Statistic by query",
     "type": "table-old",
     "gridPos": { "h": 83, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "query" ], "type": "tag" }
       ],
       "measurement": "pg_stat_statements_analyse",
       "query": "SELECT \"Calls\", top(${TOP_by}, ${TOP}), \"Total\", \"Rows\",\"Mean\", \"datname\", \"usename\", \"queryid\", \"query_md5\", \"query\" FROM \n(\nSELECT sum(\"calls\") AS \"Calls\", sum(\"duration\") AS \"Total\", sum(\"rows\") AS \"Rows\", sum(\"duration\")  / sum(\"calls\") AS \"Mean\" FROM \"$new\".\"pg_stat_statements_diff\" WHERE (\"datname\" =~ /^${datname:regex}$/ AND \"host\" =~ /^${host:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND \"query\" =~/${filter:regex}/  AND $timeFilter AND time > now()-$new GROUP BY \"host\", \"datname\", \"usename\", \"queryid\", \"query_md5\", \"query\"\n),\n(\nSELECT sum(\"calls\") AS \"Calls\", sum(\"duration\") AS \"Total\", sum(\"rows\") AS \"Rows\", sum(\"duration\")  / sum(\"calls\") AS \"Mean\" FROM \"$archive\".\"pg_stat_statements_diff\" WHERE (\"datname\" =~ /^${datname:regex}$/ AND \"host\" =~ /^${host:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND \"query\" =~/${filter:regex}/  AND $timeFilter AND time < now()-$new GROUP BY \"host\", \"datname\", \"usename\", \"queryid\", \"query_md5\", \"query\"\n)",
       "select": [
        [
         { "params": [ "calls" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Calls" ], "type": "alias" }
        ],
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ],
        [
         { "params": [ "rows" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Rows" ], "type": "alias" }
        ],
        [
         { "params": [ "max_time" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Max" ], "type": "alias" }
        ],
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / sum(\"calls\")"
          ],
          "type": "math"
         },
         { "params": [ "Mean" ], "type": "alias" }
        ],
        [
         { "params": [ "shared_blks_hit" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / ( sum(\"shared_blks_hit\") + sum(\"shared_blks_read\"))"
          ],
          "type": "math"
         },
         { "params": [ "% Shared Hit" ], "type": "alias" }
        ],
        [
         { "params": [ "local_blks_hit" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / ( sum(\"local_blks_hit\") + sum(\"local_blks_read\"))"
          ],
          "type": "math"
         },
         { "params": [ "% Local Hit" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}