- hosts: 127.0.0.1
  connection: local
  gather_facts: false

  vars_files:
    - ../labconfig.yml

  tasks:
    - name: Setup network
      include_tasks: 
        file: setup-network.yml

  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted