---

  # minpoll and maxpoll is specified in 2 power of second
  # minpoll 0 - 1 second
  # maxpoll 5 - 32 second
  - name: Tweak chronyd time polling
    lineinfile: 
      dest: /etc/chrony/chrony.conf
      regexp: '^pool.*$' 
      line: "pool pool.ntp.org iburst minpoll 0 maxpoll 5" 
      state: present