---

- name: Install PostgreSQL
  hosts: database
  gather_facts: false

  roles:
    - common
    - telegraf-node
    - postgresql
    - wp-db-setup-postgresql

- name: Convert MariaDB
  hosts: database
  gather_facts: false

  roles:
    - wp-db-convert-mysql-2-postgresql

- name: Install Wordpress
  hosts: web
  gather_facts: false

  roles:
    - common
    - telegraf-node
    - php-fpm
    - nginx
    - wordpress
    - wordpress-plugins
