---

  - name: Install Grafana
    yum:
      name: "https://dl.grafana.com/oss/release/{{grafana_version_rpm}}"
      state: present
    when: config_only == false

  - name: Install/update Grafana piechart panel plugin
    community.grafana.grafana_plugin:
      name: grafana-piechart-panel
      version: latest
      state: present

  - name: Install/update Grafana yesoreyeram-boomtable-panel
    community.grafana.grafana_plugin:
      name: yesoreyeram-boomtable-panel
      version: latest
      state: present
